// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwoR0UE2_y-5a4LsXVis2wS3YQnCKfF7Q',
    appId: '1:980995994159:web:ffc44037c2b05ec4cb8cda',
    messagingSenderId: '980995994159',
    projectId: 'log-o-logu',
    authDomain: 'log-o-logu.firebaseapp.com',
    storageBucket: 'log-o-logu.firebasestorage.app',
    measurementId: 'G-1WWJCV04Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpe4N_l-YrD_narWWzkEJrpjGmX5N0Tn8',
    appId: '1:980995994159:android:f93b78daa15e8189cb8cda',
    messagingSenderId: '980995994159',
    projectId: 'log-o-logu',
    storageBucket: 'log-o-logu.firebasestorage.app',
  );
}
